name: Build, Scan and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Machine virtuelle sur laquelle le workflow sera exécuté

    steps:
      # 1. Récupérer le code source du repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Se connecter au registre GitHub Container Registry
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest .

      # 4. Scanner l'image Docker avec Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.6.0
        with:
          image: ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
          format: 'table'
        continue-on-error: true

      # 5. Pousser l'image Docker vers GitHub Packages
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
